version: "3"

services:

  books-redis-pubsub:
    build:
      context: .
      dockerfile: ./books/Dockerfile
    image: book-image
    container_name: books-redis-pubsub
    depends_on:
      # - postgres
      - redis
      # - mailhog
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - REDIS_HOST=redis
      - EMAIL_HOST=mailhog
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./books:/src/books
    entrypoint:
      - python
      - -m
      - books.redis_eventconsumer

  books-api:
    image: book-image
    container_name: books-api
    build:
      context: .
      dockerfile: ./books/Dockerfile
      target: debug
    depends_on:
      - books-redis-pubsub
      # - mailhog
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - API_HOST=0.0.0.0
      - REDIS_HOST=redis
      - EMAIL_HOST=mailhog
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=books/app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./books:/src/books
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "books.app",  "--wait-for-client", "--multiprocess", "-m", "flask", "run"]
      # - flask
      # - run
      # - --host=0.0.0.0
      # - --port=5000
    ports:
      - "5000:5000"
      - 5678:5678

  # postgres:
  #   image: postgres:9.6
  #   environment:
  #     - POSTGRES_USER=allocation
  #     - POSTGRES_PASSWORD=abc123
  #   ports:
  #     - "54321:5432"

  redis:
    image: redis:alpine
    ports:
      - "63791:6379"

  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - "11025:1025"
  #     - "18025:8025"

  prometheus:
    image: prom/prometheus:latest
    command: "--config.file=/etc/prometheus/prometheus.yml --web.listen-address '0.0.0.0:9090'"
    ports:
      - "9090:9090"
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml